### ISSUE TITLE
If you need help let me know

### ISSUE THREAD

**Issue by tiagobrito** [cloudtek/dynamodm#1]
Hi @aaronm-cloudtek congrats for this OSS project, this is a great initiative. I work on daily base with aws DynamoDB SDK, if you need some help let me know.

**Comment by aaronm-cloudtek** [comment]
Hello @tiagobrito, thanks for reaching out! I appreciate your kind words.

I welcome any collaboration, be it testing, code review, pull requests or even just feedback on design decisions.

At this point things are still changing fairly rapidly but I hope to release an alpha soon, at which point I was planning to seek input from the community. That would be a great time for you or anyone else interested to get involved.

Cheers :)

**Comment by tiagobrito** [comment]
I will wait for the alpha. I already try it, but I'm having some problems:

*   `No primary index specified for document 'AppBundle\Document\MyEnity'. Every Document must have a primary index.``

with the following entity:

```php
/**
 * @Document(table="myentity")
 */
class MyEntity
{
    private $id;

    public function id(): int
    {
        return $this->id;
    }
}
```

And I also add to add this method `setDefaultCommitOptions` to Cloudtek\ODM\DynamoDB\Configuration.php 👍 

```php
    public function setDefaultCommitOptions( $defaultCommitOptions )
    {
        $this->attributes['defaultCommitOptions'] = $defaultCommitOptions;
    }
```
due to:
> Attempted to call an undefined method named "setDefaultCommitOptions" of class "Cloudtek\ODM\DynamoDB\Configuration".

**Comment by aaronm-cloudtek** [comment]
Yeah it's not in a working state currently. I wrote a lot of code without testing it, just to get the design fleshed out. Now I'm going back and writing tests and fixing bugs.

I should have something more stable in a couple weeks or so if you want to check back then.

**Comment by aaronm-cloudtek** [comment]
"A couple weeks" haha. So it's really nearly finished now. One of the of the last remaining milestones is the `DynamoDM\Client` namespace, which contains all the logic for mapping query operations to AWS SDK calls. Do you have much experience with the DynamoDB php api, specifically in regards to batching and pooling operations? That's where I'm at now, it would be great to have another dev to collaborate with on if you are still interested and have time. 

Other than that the bundle needs to be touched up and better test coverage will be needed, although I've converted a fair number of tests of Mongo ODM so far and the core functionality is pretty much verified. Once all that's done I will tag a release and submit it to the wider community for feedback.

**Comment by aaronm-cloudtek** [comment]
By the way, the issue with the document you pasted above is that an ODM attribute with the `@HashKey` annotation is required for non-embedded documents.

```
/**
  * @ODM\Attribute(type="string")
  * @ODM\HashKey
  */
private $id;
```

I just updated that error message to be more clear, thanks for helping me catch that.
